### ISSUE TITLE
Support for more monitoring features

### ISSUE THREAD

**Issue by LukasFratzl** [lfreist/hwinfo#50]
Hey, I'm building a private app with hwinfo, I miss some monitoring features, before I end up building this missing parts myself I need to know if it's on the way, otherwise I will do a pull request if I get it done.... what I miss is:

 - Temperatures for CPU, GPU | Linux, Windows
 - Utilization for CPU, GPU | Linux, Windows
 - Memory In Use | Memory Max for GPU | Linux Windows
 
 Is this on the Roadmap?
 
I use an NVIDIA GPU, so this makes things a lot easier
As well as Current Frequency of my CPU returns the same as the base frequency while I'm getting other results in the windows task manager....
I see there is a lot of stuff already supported but not implemented, like the OpenCL library has a lot...

**Comment by lfreist** [comment]
Hi,

A brief summary of my thoughts of the last few minutes:

- For Linux, temperatures can be accessed using [lm_sensors](https://wiki.archlinux.org/title/lm_sensors). Including this information in HWinfo most likely would mean to add lm_sensors as dependency
- For Windows, temperatures can be accessed via WMI. If it is included to HWinfo or not, you can use the [WMI-wrapper provided by HWinfo](https://github.com/lfreist/hwinfo/blob/main/include/hwinfo/WMIwrapper.h) to query those information.
- GPU Memory: afaik, OpenCL only allows to query for the total local/global memory size rather than the available memory size.

I am still thinking about the inclusion of these information into HWinfo (especially the available mem for GPUs) but even if I decide to include them, it will take some time.

So I'd be happy to see your implementations to decide about a merge.

Thanks and Greetings

Leon

**Comment by LukasFratzl** [comment]
Thanks a lot for considering it,

Hardware programming is fairly new to me, I'm professional Game Developer and mostly 99% at the time working with high level implementations like the enhanced Unreal engine api, but I made today some tests with chat gpt and .bat scripts and come across really useful stuff like monitoring cpu, gpu utilisations, current processing speed with include intels boost frequency and I call it a day... 

I even though about just making a .bat script loop while writing the data to a file and reading the file with the server, but underneath the ground it's just calling a library somewhere which is kind of cheating^^ so I will definitely try to implement it into hwinfo, and having it later in the repo would be cool but it's up to you anyway...

I'm currently in holiday as well so I can give this following 2 weeks my full attention into the implementation of the features I need.

Best wishes
